=== husoczkidani/HLO5ZK_XMLGyak/HLO5ZK_0928/HD_konyv.dtd
<!ELEMENT konyvek (konyv*)>
<!ELEMENT konyv (cim,kiadasiev,kiado,szerzo+)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasiev (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>

=== husoczkidani/HLO5ZK_XMLGyak/HLO5ZK_0928/HD_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyv SYSTEM "HD_konyv.dtd">
<konyvek>
	<konyv id="1" >
		<cim>Clean Code</cim>
		<kiadasiev>1999. szeptember</kiadasiev>
		<kiado>valakik 1</kiado>
		<szerzo>valaki 1 1</szerzo>
		<szerzo>valaki 1 2</szerzo>
	</konyv>
	
	<konyv id="2" >
		<cim>Clean Architecture</cim>
		<kiadasiev>1987. szeptember</kiadasiev>
		<kiado>valakik 2</kiado>
		<szerzo>valaki 2</szerzo>
	</konyv>
</konyvek>
